title: Cunxuan Jiang's Homepage
page-top-title: Cunxuan Jiang
top-section-bg-text: Welcome! Amigo!
home-subtitle: Cunxuan Jiang&ensp;|&ensp;Jacob
copyright-text: '&copy; Cunxuan Jiang 2023-2025. All Rights Reserved.'
